export const ChairList = [
  {
    id: 1,
    src: "/img/chair/1.webp",
    title: "Pratap chair1",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 2,
    src: "/img/chair/2.webp",
    title: "Pratap chair2",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 3,
    src: "/img/chair/3.webp",
    title: "Pratap chair3",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 4,
    src: "/img/chair/4.webp",
    title: "Pratap chair4",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 5,
    src: "/img/chair/5.webp",
    title: "Pratap chair5",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 6,
    src: "/img/chair/1.webp",
    title: "Pratap chair6",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 7,
    src: "/img/chair/7.webp",
    title: "Pratap chair7",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },

  {
    id: 10,
    src: "/img/chair/10.webp",
    title: "Pratap chair10",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },

  {
    id: 12,
    src: "/img/chair/12.webp",
    title: "Pratap chair12",
    description: "Pratap chair is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
];
