export const SofaList = [
  {
    id: 1,
    src: "/img/sofa/12.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 2,
    src: "/img/sofa/11.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 3,
    src: "/img/sofa/10.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 4,
    src: "/img/sofa/4.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 5,
    src: "/img/sofa/5.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 6,
    src: "/img/sofa/6.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 7,
    src: "/img/sofa/7.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 8,
    src: "/img/sofa/8.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 9,
    src: "/img/sofa/9.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 10,
    src: "/img/sofa/3.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 11,
    src: "/img/sofa/2.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 12,
    src: "/img/sofa/1.webp",
    title: "Pratap sofa",
    description: "Pratap sofa is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
];
