export const BedList = [
  {
    id: 1,
    src: "/img/bed/12.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 2,
    src: "/img/bed/11.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 3,
    src: "/img/bed/10.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 4,
    src: "/img/bed/4.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 5,
    src: "/img/bed/5.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 6,
    src: "/img/bed/6.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 7,
    src: "/img/bed/7.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 8,
    src: "/img/bed/8.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 9,
    src: "/img/bed/9.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 10,
    src: "/img/bed/3.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 11,
    src: "/img/bed/2.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 12,
    src: "/img/bed/1.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
];
