export const Bestproduct = [
  {
    id: 1,
    src: "/img/product.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 2,
    src: "/img/product1.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 3,
    src: "/img/product2.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 4,
    src: "/img/product3.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 5,
    src: "/img/product4.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
  {
    id: 6,
    src: "/img/product6.webp",
    title: "Pratap Bed",
    description: "Pratap Bed is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "30",
  },
];
