export const DoorList = [
  {
    id: 1,
    src: "/img/door/1.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 2,
    src: "/img/door/2.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 3,
    src: "/img/door/3.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 4,
    src: "/img/door/4.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 5,
    src: "/img/door/5.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 6,
    src: "/img/door/1.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 7,
    src: "/img/door/7.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 8,
    src: "/img/door/8.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 9,
    src: "/img/door/9.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 10,
    src: "/img/door/10.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 11,
    src: "/img/door/11.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
  {
    id: 12,
    src: "/img/door/12.webp",
    title: "Pratap door",
    description: "Pratap door is Lorem ipsum dolor sit amet",
    Price: "10000",
    discount: "50",
  },
];
